### PR TITLE
Fix TypeError in _ensure_bool: str has no attribute 'tolower'

### PR DESCRIPTION
**Pull request by zjhuntin**
## Summary

`_ensure_bool` in `pulpcore/app/tasks/export.py` (introduced in 438bdc8e) calls `value.tolower()` which does not exist on Python strings. This causes incremental content exports to fail with:

```
Error: 'str' object has no attribute 'tolower'
```

Fix changes both occurrences to `value.lower()`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by ggainey — APPROVED** [review]

**Review by ggainey — CHANGES_REQUESTED** [review]
Zach - 7571 is fixed, this is its own bugfix.  You can add changelog entries without a specific github issue - see https://pulpproject.org/pulpcore/docs/dev/guides/git/#changelog-update , you can name the changefile something like "+fix_ensure_bool.bugfix"

**Comment by jobselko** [comment]
We actually have an issue for this. @zjhuntin Could you please update your commit to mention #7678?

File: CHANGES/7678.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fixed `TypeError: 'str' object has no attribute 'tolower'` in `_ensure_bool` during incremental content exports. Changed `.tolower()` to `.lower()`.
```
Comment (mdellweg) [inline CHANGES/7678.bugfix:1]: You would indeed need to find another issue, or, (probably easier now) rename this file to `+no-tolower.bugfix`.

**Comment by ggainey** [comment]
> We actually have an issue for this. @zjhuntin Could you please update your commit to mention #7678?

Good catch - that will teach me to respond without searching first... :)

File: CHANGES/7678.bugfix (hunk 1 above)
Comment (mdellweg) [reply CHANGES/7678.bugfix:1]: nm @jobselko beat me to it...

**Comment by zjhuntin** [comment]
Apologies, will update it, thank you all for the feedback! :smile:

**Review by ggainey — APPROVED** [review]

**Comment by ianballou** [comment]
Katello would like to request a 3.105 backport for this.

**Comment by ggainey** [comment]
> Katello would like to request a 3.105 backport for this.

Will backport to everything the original PR (#7651) went to.
