### ISSUE TITLE
Fix TypeError in _ensure_bool: str has no attribute 'tolower'

### ISSUE THREAD

**Issue by zjhuntin** [pulp/pulpcore#7678]
## Summary

`_ensure_bool` in `pulpcore/app/tasks/export.py` (introduced in commit 438bdc8e) calls `value.tolower()` on Python strings. Python strings have no `.tolower()` method — the correct method is `.lower()`. This causes a `TypeError: 'str' object has no attribute 'tolower'` whenever `hammer content-export incremental` is used.
